<?php
/**
 * module-testcase:/form/conversion.phtml
 *
 * @creation  2017-08-24
 * @version   1.0
 * @package   app-skeleton
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
/* @var $form Form */
$form->Clear();
?>
<script>
document.addEventListener('DOMContentLoaded', function(){
	setTimeout(window.location.href = 'thanks.html', 0);
}, false );
</script>
