<?php
/**
 * app-skeleton-3:/html/testcase/form/form.phtml
 *
 * @creation  2017-08-23
 * @version   1.0
 * @package   onepiece-framework.com
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
?>
<article>
	<h1>Form page</h1>
	<?= $form->Start() ?>
		<div role="table">
			<?php foreach(['text','textarea','select','radio','checkbox'] as $name): ?>
			<div role="tr">
				<div role="th">
					<?= $form->Label($name) ?>
				</div>
				<div role="td">
					<?= $form->Input($name) ?><br/>
					<?= $form->Error($name, 'p', 'red') ?>
				</div>
			</div>
			<?php endforeach; ?>
			<div role="tr">
				<div role="th">
					<!-- empty -->
				</div>
				<div role="td">
					<?= $form->Input('agree') ?><br/>
					<?= $form->Error('agree','p','red') ?>
					<?= $form->Input('submit') ?>
				</div>
			</div>
		</div>
	<?= $form->Finish() ?>
</article>
