<?php
/**
 * module-testcase:/unit/menu.phtml
 *
 * @creation  2018-01-23
 * @version   1.0
 * @package   module-testcase
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
$dir = ConvertURL(__DIR__);
?>
<ul>
	<li><a href="<?= "$dir/db/" ?>">Database</a></li>
	<li><a href="<?= "$dir/sql/" ?>">SQL</a></li>
	<li><a href="<?= "$dir/form/" ?>">Form</a></li>
	<li><a href="<?= "$dir/validate/" ?>">Validate</a></li>
	<li><a href="<?= "$dir/orm/" ?>">ORM</a></li>
	<li><a href="<?= "$dir/selftest/" ?>">Selftest</a></li>
</ul>
