<?php
/**
 * module-testcase:/database/menu.php
 *
 * @creation  2017-08-22
 * @version   1.0
 * @package   app-skeleton
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */
?>
<ul>
	<li><a href="app">app</a></li>
	<li><a href="quick">quick</a></li>
	<li><a href="insert">insert</a></li>
	<li><a href="select">select</a></li>
	<li><a href="update">update</a></li>
	<li><a href="delete">delete</a></li>
</ul>
